### ISSUE TITLE
Picture in Slideshow

### ISSUE THREAD

**Issue by Ravens62** [project-owner/Peppy#32]
I can't seem to set up a folder for images for the slideshow.
As long as I don't change the menu items, using the :
/home/pi/Pictures
But if I change something in the menu, like I don't want Stocks, Clock, etc. the folder doesn't work anymore, and I can't undo that by resetting the menu to the original state either.

**Comment by project-owner** [comment]
The issue was fixed and the changed file can be loaded this way:
```
cd Peppy
git fetch
git checkout origin/master -- screensaver/slideshow/slideshow.py
```
Please let me know if it works.
Thank you!

**Comment by Ravens62** [comment]
Hi,
Looks like it's working, I can change the combinations of savers and still have a valid folder for Slideshow.
Thanks
